; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                  = 7160929-64-bit MS Windows           
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = False                               
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
[ ProcessTypes ]
ppAncSeq                             = true                                
ppML                                 = true                                
[ AnalysisSettings ]
Analysis                             = Ancestral Sequence Inference        
Tree to Use                          = Use tree from file                  
Statistical Method                   = Maximum Likelihood                  
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = Jukes-Cantor model                  
Rates and Patterns                   = ====================                
Rates among Sites                    = Gamma Distributed (G)               
No of Discrete Gamma Categories      = 5                                   
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = Use all sites                       
Site Coverage Cutoff (%)             = Not Applicable                      
Branch Swap Filter                   = None                                
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
